import { Badge } from "@/components/ui/badge";

export function TargetForecast({ forecast }: { forecast: { month: string; delivered: number; target: number; projected: number; remainingDays: number; gap: number; confidence: "low" | "medium" } }) {
  const attainment = forecast.target ? forecast.delivered / forecast.target : 0;
  const projectedAttainment = forecast.target ? forecast.projected / forecast.target : 0;
  const label = projectedAttainment >= 1 ? "On track" : projectedAttainment >= .85 ? "At risk" : "Likely miss";
  const variant = projectedAttainment >= 1 ? "success" : projectedAttainment >= .85 ? "warning" : "danger";
  return <div><div className="flex items-end justify-between"><div><div className="text-sm font-medium text-[#667085]">Latest month target</div><div className="mt-2 text-3xl font-bold tracking-[-.04em]">{forecast.delivered} <span className="text-lg font-medium text-[#98a2b3]">/ {forecast.target}</span></div></div><Badge variant={variant}>{label}</Badge></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-[#edf0f3]"><div className={projectedAttainment >= 1 ? "h-full rounded-full bg-[#14966b]" : projectedAttainment >= .85 ? "h-full rounded-full bg-[#df8b14]" : "h-full rounded-full bg-[#d54b4b]"} style={{ width: `${Math.min(100, Math.max(4, attainment*100))}%` }}/></div><div className="mt-3 flex justify-between text-xs text-[#667085]"><span>{Math.round(attainment*100)}% attained</span><span>{forecast.remainingDays} days left</span></div><div className="mt-4 rounded-xl bg-[#f7f8fa] p-3 text-xs leading-5 text-[#566070]">{forecast.remainingDays > 0 ? <>Pipeline-weighted projection: <strong className="text-[#111827]">{forecast.projected.toFixed(1)} units</strong>. This uses historical stage-to-delivery conversion, not a black-box model.</> : <>The selected month is complete. Final result: <strong className="text-[#111827]">{forecast.delivered} units</strong>{forecast.gap > 0 ? `, ${Math.ceil(forecast.gap)} below target.` : ", target met."}</>}</div></div>;
}
